### ISSUE TITLE
Some sources of MT560 are likely to be polluted

### ISSUE THREAD

**Issue by ZJaume** [laurieburchell/open-lid-dataset#1]
Mt560 lists Paracrawl, Wikimatrix and OPUS100 as sources. Some of these are likely to be polluted. Wikimatrix IIRC sometimes contains sentences in other language, Paracrawl for sure as it comes from the web and language is identified with cld2 and fasttext, and OPUS100 contains a mix of corpora from OPUS that some of them can also be polluted.

Is this dataset containing data from there?

**Comment by laurieburchell** [comment]
Thanks for raising the issue. We actually filtered out a lot of the sources in MT560 v1 for the reasons you mentioned around the fidelity of the language labels. Specifically, we excluded all sentences in MT560 sourced from OPUS-100, Europarl, Open Subtitles, Paracrawl, Wikimedia, Wikimatrix, Wikititles, and Common Crawl. I've updated the repo to reflect this and I'll add a clarification in the paper.
