### ISSUE TITLE
add probability of the language label

### ISSUE THREAD

**Issue by ZeroneBo** [laurieburchell/open-lid-dataset#9]
Hi, it's a great work!

Are there some ways to output the probability of the language label given a label? If not, could you share a script to get the probability of the given label?

Thank you for any helpful suggestions!

**Comment by laurieburchell** [comment]
You can run `fasttext predict-prob` rather than `fasttext predict`. See the [fasttext documentation](https://fasttext.cc/docs/en/cheatsheet.html) for more details. There's a link to the fasttext documentation in the repo, so I'll leave the provided scripts as is. Hope that helps!
